### ISSUE TITLE
Providing multiple VCFs to vireo

### ISSUE THREAD

**Issue by onecarbon** [single-cell-genetics/vireo#2]
Thanks for your work on this!

I'm trying to run vireo on multiple outputs from cellSNP (as per this in your paper:  'If  cells  from the same individuals are assayed in multiple batches, Vireo can also demultiplex them jointly...').

Any advice on the syntax to do this is appreciated!

**Comment by huangyh09** [comment]
Thanks for mentioning this practical issue. We initially append the sparse matrices of AD and DP from mulitple data sets, namely this step requires some manually processing, e.g., with scipy. We will provide an interface to combine them in VCF formats, hopefully very soon.

Yuanhua

**Comment by finnhamilton** [comment]
Thanks for clarifying-- I look forward to trying it out

**Comment by cohenp05** [comment]
Hello @huangyh09 
Thanks for this great software. I'm wondering if there are any updates on how I should merge multiple VCFs for vireo. Due to the size of my dataset, I had to run cellSNP on a separate node per chromosome, and it's not clear to me how to append the output into one file to input into vireo. Any help would be much appreciated!

Thanks
Phil

**Comment by huangyh09** [comment]
Hi @cohenp05 there could be two ways to combine the data:
1) using bcftools concat: http://www.htslib.org/doc/bcftools.html#concat
2) load the sparse matrices with scipy and append them; or use [vireoSNP.load_cellSNP](https://github.com/single-cell-genetics/vireo/blob/master/vireoSNP/utils/io_utils.py#L11) and append each item in the dictionary. You may get some hints from here: https://github.com/single-cell-genetics/vireo/blob/master/examples/vireoSNP_donors.ipynb

In case you only have vcf as output from cellSNP, you could convert it sparse matrices by this code: https://github.com/single-cell-genetics/cellSNP/blob/master/test/VCF_convert.py

I would suggest you trying bcftools firs since it is just a single command line. If it produces too large vcf files, you could consider the sparse matrix.

Yuanhua

**Comment by huangyh09** [comment]
Also, it is good to pre-filter some variants before giving it to vireo, e.g., DP>minCOUNT, AD/DP>minMAF, AD/DP<1-minMAF, all at bulk level. These threshold may depends on the data set size.
